### ISSUE TITLE
RISCV Support

### ISSUE THREAD

**Issue by HougeLangley** [moonbitlang/moon#452]
# Feature Request
RISCV Support
**Note:** While we appreciate all feature requests, please understand that not all requests can be accepted. Providing detailed information will help us better evaluate your suggestion.

目前测试是否能够在最新的 Archlinux 上编译通过。整个流程如下：

1. git clone https://github.com/moonbitlang/moon.git
2. cd moon
3. 配置编译环境避免以下 rust_v8 问题

```
error: failed to run custom build command for `v8 v0.106.0`

Caused by:
  process didn't exit successfully: `/home/houge/moon/target/release/build/v8-bd77a7ea4500718d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=.gn
  cargo:rerun-if-changed=BUILD.gn
  cargo:rerun-if-changed=src/binding.cc
  cargo:rerun-if-env-changed=CCACHE
  cargo:rerun-if-env-changed=CLANG_BASE_PATH
  cargo:rerun-if-env-changed=CXXSTDLIB
  cargo:rerun-if-env-changed=DENO_TRYBUILD
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=GN
  cargo:rerun-if-env-changed=GN_ARGS
  cargo:rerun-if-env-changed=HOST
  cargo:rerun-if-env-changed=NINJA
  cargo:rerun-if-env-changed=OUT_DIR
  cargo:rerun-if-env-changed=RUSTY_V8_ARCHIVE
  cargo:rerun-if-env-changed=RUSTY_V8_MIRROR
  cargo:rerun-if-env-changed=RUSTY_V8_SRC_BINDING_PATH
  cargo:rerun-if-env-changed=SCCACHE
  cargo:rerun-if-env-changed=V8_FORCE_DEBUG
  cargo:rerun-if-env-changed=V8_FROM_SOURCE
  cargo:rerun-if-env-changed=PYTHON
  cargo:rerun-if-env-changed=DISABLE_CLANG
  cargo:rerun-if-env-changed=EXTRA_GN_ARGS
  cargo:rerun-if-env-changed=PRINT_GN_ARGS
  cargo:rerun-if-env-changed=CARGO_ENCODED_RUSTFLAGS
  cargo:rustc-link-lib=static=rusty_v8
  lockfile: "/home/houge/moon/target/release/build/v8.fslock"
  cargo:rustc-env=RUSTY_V8_SRC_BINDING_PATH=/home/houge/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.106.0/gen/src_binding_release_riscv64gc-unknown-linux-gnu.rs
  static lib URL: https://github.com/denoland/rusty_v8/releases/download/v0.106.0/librusty_v8_release_riscv64gc-unknown-linux-gnu.a.gz
  cargo:rustc-link-search=/home/houge/moon/target/release/gn_out/obj
  Looking for download in '"/home/houge/.cargo/.rusty_v8/https___github_com_denoland_rusty_v8_releases_download_v0_106_0_librusty_v8_release_riscv64gc_unknown_linux_gnu_a_gz"'
  Downloading (using Python) https://github.com/denoland/rusty_v8/releases/download/v0.106.0/librusty_v8_release_riscv64gc-unknown-linux-gnu.a.gz
  Downloading https://github.com/denoland/rusty_v8/releases/download/v0.106.0/librusty_v8_release_riscv64gc-unknown-linux-gnu.a.gz...
  HTTP Error 404: Not Found
  Python downloader failed, trying with curl.

  --- stderr
  Traceback (most recent call last):
    File "/home/houge/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.106.0/./tools/download_file.py", line 64, in <module>
      sys.exit(main())
               ^^^^^^
    File "/home/houge/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.106.0/./tools/download_file.py", line 59, in main
      DownloadUrl(args.url, f)
    File "/home/houge/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.106.0/./tools/download_file.py", line 45, in DownloadUrl
      raise e
    File "/home/houge/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.106.0/./tools/download_file.py", line 29, in DownloadUrl
      response = urlopen(url)
                 ^^^^^^^^^^^^
    File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
      return opener.open(url, data, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/urllib/request.py", line 521, in open
      response = meth(req, response)
                 ^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/urllib/request.py", line 630, in http_response
      response = self.parent.error(
                 ^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/urllib/request.py", line 559, in error
      return self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
      result = func(*args)
               ^^^^^^^^^^^
    File "/usr/lib/python3.12/urllib/request.py", line 639, in http_error_default
      raise HTTPError(req.full_url, code, msg, hdrs, fp)
  urllib.error.HTTPError: HTTP Error 404: Not Found
  thread 'main' panicked at /home/houge/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.106.0/build.rs:527:3:
  assertion failed: status.success()
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

详细配置方案是，在 archlinux riscv 下安装 clang ninja gn python ，随后设置环境变量

```
export CC=clang
export CXX=clang++
export V8_FROM_SOURCE=1
export GN=/usr/bin/gn
export NINJA=/usr/bin/ninja
export EXTRA_GN_ARGS="v8_enable_shared_ro_heap=false"
```

**Comment by Young-Flash** [comment]
related to https://github.com/denoland/rusty_v8/issues/1476

**Comment by lynzrand** [comment]
This is a stale issue. The V8 side has been closed, so I'm closing this too. Feel free to reopen if the problem still persists.
